<a href="https://colab.research.google.com/github/jlaurencio/esp32-firmware-update/blob/main/Copia_de_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense  # Import Dense directly from keras.layers

# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[0.16,0.1,0.11,0.02,0.02,0.17],[0.03,0.01,0.02,0.02,0.01,0.03],[0.01,0.01,0,0,0,0],[0.01,0,0,0.01,0,0],[0.01,0,0,0,0,0.01],[0,0,0.01,0.01,0,0],[0,0,0.01,0,0,0.01],[0,0,0,0,0.01,0.01],[0.06,0.01,0.03,0.03,0.01,0.06],[0.17,0.05,0.11,0.03,0.01,0.21]], "float32")
print(training_data)
# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[0.1,0,0,0.01,0.01,0,0.05,0.1,0.02],[0.01,0,0,0.01,0.01,0,0.01,0.01,0.01],[0.01,0,0,0,0,0,0,0,0],[0,0,0,0.01,0,0,0,0,0],[0,0,0,0,0,0,0.01,0,0],[0,0,0,0,0.01,0,0,0,0],[0,0,0,0,0,0,0,0.01,0],[0,0,0,0,0,0,0,0,0.01],[0.01,0,0,0.02,0.01,0,0.03,0.02,0.01],[0.05,0,0,0.02,0.01,0,0.1,0.1,0.01]], "float32")

model = Sequential()
model.add(Dense(100, input_dim=6, activation='relu')) # Changed import to reflect updated Keras API
model.add(Dense(9, activation='sigmoid')) # Changed import to reflect updated Keras API

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=1000)

# evaluamos el modelo
scores = model.evaluate(training_data, target_data)

print(scores)

print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print (model.predict(training_data))


[[0.16 0.1  0.11 0.02 0.02 0.17]
 [0.03 0.01 0.02 0.02 0.01 0.03]
 [0.01 0.01 0.   0.   0.   0.  ]
 [0.01 0.   0.   0.01 0.   0.  ]
 [0.01 0.   0.   0.   0.   0.01]
 [0.   0.   0.01 0.01 0.   0.  ]
 [0.   0.   0.01 0.   0.   0.01]
 [0.   0.   0.   0.   0.01 0.01]
 [0.06 0.01 0.03 0.03 0.01 0.06]
 [0.17 0.05 0.11 0.03 0.01 0.21]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - binary_accuracy: 0.3333 - loss: 0.2423
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - binary_accuracy: 0.5889 - loss: 0.2414
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - binary_accuracy: 0.6333 - loss: 0.2405
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - binary_accuracy: 0.6556 - loss: 0.2396
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - binary_accuracy: 0.6667 - loss: 0.2387
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - binary_accuracy: 0.6667 - loss: 0.2379
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - binary_accuracy: 0.6667 - loss: 0.2369
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - binary_accuracy: 0.6667 - loss: 0.2360
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - binary_accuracy: 0.6667 - loss: 0.2351
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - binary_accuracy: 0.6667 - loss: 0.2341
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - binary_accuracy: 0.6667 - 

In [4]:
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print (model.predict(np.array([[0.16,0.1,0.11,0.02,0.02,0.17]])))


compile_metrics: 66.67%
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step
[[0.00567513 0.00274122 0.00326936 0.00329391 0.00381519 0.00342208
  0.00529528 0.00480519 0.00343913]]
